LyeDecathlon/LyeDecathlon/Controllers/AthleteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LyeDecathlon.Models;

namespace LyeDecathlon.Controllers
{
	[Authorize]
	public class AthleteController : Controller
	{
		private DecathlonContext db = new DecathlonContext();

		//
		// GET: /Default1/

		public ActionResult Index()
		{
			return View(db.Athletes.ToList());
		}

		//
		// GET: /Default1/Details/5

		public ActionResult Details(int id = 0)
		{
			Athlete athlete = db.Athletes.Find(id);
			if (athlete == null)
			{
				return HttpNotFound();
			}
			return View(athlete);
		}

		

		//
		// GET: /Default1/Create

		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Default1/Create

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Athlete athlete)
		{
			if (ModelState.IsValid)
			{
				db.Athletes.Add(athlete);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(athlete);
		}

		//
		// GET: /Default1/Edit/5

		public ActionResult Edit(int id = 0)
		{
			Athlete athlete = db.Athletes.Find(id);
			if (athlete == null)
			{
				return HttpNotFound();
			}
			return View(athlete);
		}

		//
		// POST: /Default1/Edit/5

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Athlete athlete)
		{
			if (ModelState.IsValid)
			{
				db.Entry(athlete).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(athlete);
		}

		//
		// GET: /Default1/Delete/5

		public ActionResult Delete(int id = 0)
		{
			Athlete athlete = db.Athletes.Find(id);
			if (athlete == null)
			{
				return HttpNotFound();
			}
			return View(athlete);
		}

		//
		// POST: /Default1/Delete/5

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Athlete athlete = db.Athletes.Find(id);
			db.Athletes.Remove(athlete);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}
	}
}

LyeDecathlon/LyeDecathlon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LyeDecathlon.Models;

namespace LyeDecathlon.Controllers
{
	public class HomeController : Controller
	{
		private DecathlonContext db = new DecathlonContext();

		public ActionResult Index()
		{
			if (User.Identity.IsAuthenticated)
				return RedirectToAction("Overview");
			ViewBag.Title = "22. Sep Lye Friidrett";
			return View();
		}

		[Authorize]
		public ActionResult Overview()
		{
			var athletes = db.Athletes.ToList();
			var orderedList = athletes.OrderByDescending(x => x.Result);
			return View(orderedList);
		}

		[Authorize]
		public ActionResult Result()
		{
			var athletes = db.Athletes.ToList();
			var orderedList = athletes.OrderByDescending(x => x.Result);
			return View(orderedList);
		}

	}
}

LyeDecathlon/LyeDecathlon/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LyeDecathlon.Models;

namespace LyeDecathlon.Controllers
{
	[Authorize]
	public class ResultController : Controller
	{
		private DecathlonContext db = new DecathlonContext();

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Event(int eventId)
		{
			var eventRes = new EventResult();
			eventRes.Athletes = db.Athletes.ToList();
			eventRes.EventId = eventId;
			eventRes.EventName = GetName(eventId);
			return View(eventRes);
		}

		[HttpPost]
		public ActionResult SaveResult(int eventId, int athleteId, double? result)
		{
			
			var athlete = db.Athletes.Find(athleteId);
			if (athlete != null)
			{
				var log = new Log();
				log.AthleteName = athlete.Name;
				log.Event = GetName(eventId);
				log.Result = result;
				log.LogTime = DateTime.Now;
				switch ((EventEnum)eventId)
				{
					case EventEnum.Meter100:
						athlete.Meter100 = result;
						break;
					case EventEnum.Meter1500:
						athlete.Meter1500 = result;
						break;
					case EventEnum.Meter400:
						athlete.Meter400 = result;
						break;
					case EventEnum.Hurdles110:
						athlete.Hurdles110 = result;
						break;
					case EventEnum.LongJump:
						athlete.LongJump = result;
						break;
					case EventEnum.ShotPut:
						athlete.ShotPut = result;
						break;
					case EventEnum.HighJump:
						athlete.HighJump = result;
						break;
					case EventEnum.DiscusThrow:
						athlete.DiscusThrow = result;
						break;
					case EventEnum.PoleVault:
						athlete.PoleVault = result;
						break;
					case EventEnum.JavelinThrow:
						athlete.JavelinThrow = result;
						break;
					default:
						return Content("Could not find event");
				}
				db.Logs.Add(log);
				db.SaveChanges();
				return Content("Saved");
			}
			return Content("Could not find Athlete");
		}

		private static string GetName(int eventId)
		{
			switch ((EventEnum)eventId)
			{
				case EventEnum.Meter100:
					return "100 meter";
				case EventEnum.Meter1500:
					return "1500 meter";
				case EventEnum.Meter400:
					return "400 meter";
				case EventEnum.Hurdles110:
					return "110 meter hinder";
				case EventEnum.LongJump:
					return "Lengde";
				case EventEnum.ShotPut:
					return "Kulestøt";
				case EventEnum.HighJump:
					return "Høyde";
				case EventEnum.DiscusThrow:
					return "Diskos";
				case EventEnum.PoleVault:
					return "Stavsprang";
				case EventEnum.JavelinThrow:
					return "Spyd";
				default:
					return "Batman vs SuperMan";
			}
		}
	}
}

LyeDecathlon/LyeDecathlon/Views/Home/Index.cshtml
@section featured {
	<section class="featured">
		<div class="content-wrapper">
			<hgroup class="title">
				<h1>@ViewBag.Title.</h1>
			</hgroup>
			<p>
				Velkommen
			</p>
		</div>
	</section>
}
Du må logge inn

LyeDecathlon/LyeDecathlon/Views/Home/Overview.cshtml
@model IEnumerable<LyeDecathlon.Models.Athlete>

@{
	ViewBag.Title = "Overview";
}

<h2>Overview</h2>

<h3>Registrering</h3>
@Html.ActionLink("Registrer resultat", "Index", "Result")

@Html.ActionLink("Legg til utøver", "Create", "Athlete")

<h3>Resultat</h3>
<ol class="round">
	@{
	   var pos = 1;
	   foreach (var ath in Model.Take(9))
	  {

		 var pstring = "p" + pos.ToString();
		<li class="@pstring">
			<div class="athleteName">@ath.Name </div>
			@if (ath.Result != 0)
   {
				<div class="athleteRes">@ath.Result.ToString("####")</div>
   }
   else
   {
				<div class="athleteRes">0</div>
   }
		</li>
   pos++;
	 }
	}
</ol>
@Html.ActionLink("Resultat", "Result")

LyeDecathlon/LyeDecathlon/Views/Home/Result.cshtml
@model IEnumerable<LyeDecathlon.Models.Athlete>

@{
	ViewBag.Title = "Overview";
}

<h2>Resultat</h2>

<ul class="noBullets">
	@{
	   var pos = 1;
	   foreach (var ath in Model.Take(9))
	  {
		 var pstring = "p" + pos.ToString();
		<li>
			<h3>@pos</h3>
			<div class="athleteName">@ath.Name </div>
			@if (ath.Result != 0)
   {
				<div class="athleteRes">@ath.Result.ToString("####")</div>
   }
   else
   {
				<div class="athleteRes">0</div>
   }
		</li>
   pos++;
	 }
	}
</ul>